ユーザー新規登録画面
volcite/ChiroReservationSystem pull request #3
Opened 2020-11-04 12:37 UTC by kumo2kumo

- [x] マイグレーションの作成
- [x] 要点定義にあったバリデーション追加
- [x] ユーザー登録のためのフォームリクエスト追加（ユーザー情報編集などでも使えそうなため）

- [ ] 見た目の整え（header,footer等共通部分ができてからの方がいいかなと。仮でbootstrap適用）
 

- [ ] ？？テーブル名をm_usersに変更したいかまだできていない。モデルのUser.phpの名前はそのままにしたいため。

2020-11-06 10:41 UTC, mushajobs requested changes
お疲れ様です！
機能的には大きな問題なく作成されていて大きな問題はないと思います！！
ありがとうございます！！

Topページをdevelopブランチにマージしたらヘッダーを整えてログアウト機能も作成して頂けると有難いです！
バリデーションに関して追加してほしい点がありましたので、コメントしてあります。
再度見た時に修正して頂きたい点があるかもしれませんが、少しずつ修正していければと思います。
よろしくお願いします！

2020-11-06 10:41 UTC, mushajobs commented on app/Http/Requests/UserValidation.php
> +            'password' => ['required', 'string', 'max:30', 'confirmed', 'alpha_dash'],
パスワードは8文字以上となるようにバリデーションを追加しておきましょう！！

2020-11-06 10:41 UTC, mushajobs commented on app/Http/Requests/UserValidation.php
> +            'birthday' => ['required', 'date'],
今日以降の日付は指定できないようにバリデーションを追加してみてください！

2020-11-11 15:00 UTC, mushajobs commented
バリデーションの変更と見た目の修正、コンフリクトの修正ありがとうございます！

修正点や見た目など細かいですが気になった点をお伝えします！
ご確認お願いします。

一つ私の知識不足でわからなかった点があるので説明してもらえると嬉しいです！
よろしくお願いします

2020-11-11 15:00 UTC, ghost commented on resources/views/auth/register.blade.php
> +              <small class="ml-4 text-danger">ハイフンは不要です</small>
ハイフン不必要の注意書きありがとうございます！
分かりやすくていいですね

2020-11-11 15:00 UTC, ghost commented on resources/views/auth/register.blade.php
> +                      <input class="form-check-input" type="radio" id="male" name="gender" value='0' required value="{{ old('gender') }}" >
バリデーションに引っかかって戻ってきたときに選択が解除されてしまっていました
画面遷移後に選択されていた方が親切なので修正をお願いします
こちらの記事参考にしてみてください！！
https://qiita.com/FrogWoman/items/dcfa54d565a1709982b4

2020-11-11 15:00 UTC, ghost commented on resources/views/auth/register.blade.php
> +              <div class="alert-sm alert-danger">
エラーをそれぞれの要素の部分に記述されるようにしていただいて、とても親切で有難いです！！

エラー文のdivの横幅を少し調整して頂きたいです
テキストボックスと同じ幅に狭めて角を丸くしてもらえるとよりきれいになると思います！

2020-11-11 15:00 UTC, ghost commented on resources/views/layout.blade.php
> +        <!-- FIXME CDNはいらないかも→package.json その代わり８行目のファイル-->
すみません！！
私の知識不足でよく理解できていません...
<!-- FIXME CDNはいらないかも→package.json その代わり８行目のファイル-->

少し教えて頂けると有難いです！！
よろしくお願いします

2020-11-11 15:04 UTC, mushajobs commented on resources/views/layout.blade.php
> +        <!-- FIXME CDNはいらないかも→package.json その代わり８行目のファイル-->
あ、わかりました！
css/apps.cssの事ですね！

FIXME　CDNの知識が全くなく初耳だったので調べてみます！！

2020-11-15 00:12 UTC, SakaeShinya commented on resources/views/auth/register.blade.php
> +              <small class="ml-4 text-danger">ハイフンは不要です</small>
![image](https://user-images.githubusercontent.com/63535534/99159733-abd27580-2722-11eb-9e5a-2abf7b55e1a9.png)

2020-11-15 13:48 UTC, kumo2kumo commented on resources/views/layout.blade.php
> +        <!-- FIXME CDNはいらないかも→package.json その代わり８行目のファイル-->
あ、FIXMEは自分のメモなので　CDNからがコメント本文です。ややこしくてすいません;;

2020-11-17 05:11 UTC, kumo2kumo commented
レビューを参考に見た目部分（仮）を作っています。
`/register2`で見れるので、レビューをよろしくお願いします！

2020-11-18 11:02 UTC, kumo2kumo commented
仮のviewを新しく作りましたので、レビューをお願いします。
`/register2`で飛べます

2020-11-18 18:18 UTC, mushajobs approved these changes

2020-11-18 18:18 UTC, mushajobs commented
お疲れ様です！

見た目がめっちゃきれいになっていてびっくりしました！！
ありがとうございます！
自分からは特に修正をお願いするような部分はないかなと思います。
SHINYAさんに見て頂いて、大丈夫そうでしたらマージして頂きます！

2020-11-21 01:51 UTC, SakaeShinya commented
確認致しました！
かなり見た目が整った登録画面になっていて驚きました！
バリデーションも問題なさそうなので、mergeしてよいかと思います。

2020-11-21 04:53 UTC, mushajobs commented
SHINYAさんご確認ありがとうございます！

それではマージさせて頂きます
Calugonさんお疲れ様でした！
引き続きログイン画面の作成をよろしくお願いします

2020-11-21 04:53 UTC, merged